[package]
name = "rust-book-multithreaded-web-server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "^1.4"
regex = "^1.5"
chrono = "^0.4"
